version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"  # Changed from "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scheduler
      - SESSION_SECRET=${SESSION_SECRET}
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_FROM=noreply@scheduler.com
      - APP_URL=http://localhost:3001  # Changed from http://localhost:3000
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scheduler
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  postgres_data: